package com.linngdu664.bsf.util;

import com.linngdu664.bsf.registry.ItemRegister;
import net.minecraft.core.NonNullList;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import org.jetbrains.annotations.NotNull;

public class BSFCreativeModeTab {
    public static final CreativeModeTab BSF_GROUP = new CreativeModeTab("bsf_group") {
        @Override
        public @NotNull ItemStack makeIcon() {
            return ItemRegister.EXPLOSIVE_SNOWBALL.get().getDefaultInstance();
        }

        @Override
        public void fillItemList(@NotNull NonNullList<ItemStack> pItems) {
            pItems.add(ItemRegister.SMOOTH_SNOWBALL.get().getDefaultInstance());
            pItems.add(ItemRegister.DUCK_SNOWBALL.get().getDefaultInstance());
            pItems.add(ItemRegister.COMPACTED_SNOWBALL.get().getDefaultInstance());
            pItems.add(ItemRegister.COMPACTED_SNOWBALL_SET.get().getDefaultInstance());
            pItems.add(ItemRegister.STONE_SNOWBALL.get().getDefaultInstance());
            pItems.add(ItemRegister.GLASS_SNOWBALL.get().getDefaultInstance());
            pItems.add(ItemRegister.ICE_SNOWBALL.get().getDefaultInstance());
            pItems.add(ItemRegister.IRON_SNOWBALL.get().getDefaultInstance());
            pItems.add(ItemRegister.GOLD_SNOWBALL.get().getDefaultInstance());
            pItems.add(ItemRegister.OBSIDIAN_SNOWBALL.get().getDefaultInstance());
            pItems.add(ItemRegister.EXPLOSIVE_SNOWBALL.get().getDefaultInstance());
            pItems.add(ItemRegister.THRUST_SNOWBALL.get().getDefaultInstance());
            pItems.add(ItemRegister.LIGHT_MONSTER_TRACKING_SNOWBALL.get().getDefaultInstance());
            pItems.add(ItemRegister.HEAVY_MONSTER_TRACKING_SNOWBALL.get().getDefaultInstance());
            pItems.add(ItemRegister.EXPLOSIVE_MONSTER_TRACKING_SNOWBALL.get().getDefaultInstance());
            pItems.add(ItemRegister.LIGHT_PLAYER_TRACKING_SNOWBALL.get().getDefaultInstance());
            pItems.add(ItemRegister.HEAVY_PLAYER_TRACKING_SNOWBALL.get().getDefaultInstance());
            pItems.add(ItemRegister.EXPLOSIVE_PLAYER_TRACKING_SNOWBALL.get().getDefaultInstance());
            pItems.add(ItemRegister.MONSTER_GRAVITY_SNOWBALL.get().getDefaultInstance());
            pItems.add(ItemRegister.PROJECTILE_GRAVITY_SNOWBALL.get().getDefaultInstance());
            pItems.add(ItemRegister.MONSTER_REPULSION_SNOWBALL.get().getDefaultInstance());
            pItems.add(ItemRegister.PROJECTILE_REPULSION_SNOWBALL.get().getDefaultInstance());
            pItems.add(ItemRegister.IMPULSE_SNOWBALL.get().getDefaultInstance());
            pItems.add(ItemRegister.BLACK_HOLE_SNOWBALL.get().getDefaultInstance());
            pItems.add(ItemRegister.SUBSPACE_SNOWBALL.get().getDefaultInstance());
            pItems.add(ItemRegister.POWDER_SNOWBALL.get().getDefaultInstance());
            pItems.add(ItemRegister.SPECTRAL_SNOWBALL.get().getDefaultInstance());
            pItems.add(ItemRegister.FROZEN_SNOWBALL.get().getDefaultInstance());
            pItems.add(ItemRegister.CRITICAL_FROZEN_SNOWBALL.get().getDefaultInstance());
            pItems.add(ItemRegister.ENDER_SNOWBALL.get().getDefaultInstance());
            pItems.add(ItemRegister.GHOST_SNOWBALL.get().getDefaultInstance());
            pItems.add(ItemRegister.EXPANSION_SNOWBALL.get().getDefaultInstance());
            pItems.add(ItemRegister.RECONSTRUCT_SNOWBALL.get().getDefaultInstance());
            pItems.add(ItemRegister.ICICLE_SNOWBALL.get().getDefaultInstance());

            Item tank = ItemRegister.SNOWBALL_TANK.get();
            ItemStack itemStack = tank.getDefaultInstance();
            itemStack.setDamageValue(itemStack.getMaxDamage());
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "compacted_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "stone_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "glass_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "ice_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "iron_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "gold_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "obsidian_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "explosive_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "thrust_snowball");
            pItems.add(itemStack);

            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "light_monster_tracking_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "heavy_monster_tracking_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "explosive_monster_tracking_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "light_player_tracking_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "heavy_player_tracking_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "explosive_player_tracking_snowball");
            pItems.add(itemStack);

            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "monster_gravity_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "monster_repulsion_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "projectile_gravity_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "projectile_repulsion_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "impulse_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "black_hole_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "subspace_snowball");
            pItems.add(itemStack);

            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "powder_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "spectral_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "frozen_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "critical_frozen_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "ender_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "ghost_snowball");
            pItems.add(itemStack);

            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "expansion_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "reconstruct_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "icicle_snowball");
            pItems.add(itemStack);


            tank = ItemRegister.LARGE_SNOWBALL_TANK.get();
            itemStack = tank.getDefaultInstance();
            itemStack.setDamageValue(itemStack.getMaxDamage());
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "compacted_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "stone_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "glass_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "ice_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "iron_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "gold_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "obsidian_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "explosive_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "thrust_snowball");
            pItems.add(itemStack);

            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "light_monster_tracking_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "heavy_monster_tracking_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "explosive_monster_tracking_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "light_player_tracking_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "heavy_player_tracking_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "explosive_player_tracking_snowball");
            pItems.add(itemStack);

            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "monster_gravity_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "monster_repulsion_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "projectile_gravity_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "projectile_repulsion_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "impulse_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "black_hole_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "subspace_snowball");
            pItems.add(itemStack);

            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "powder_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "spectral_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "frozen_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "critical_frozen_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "ender_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "ghost_snowball");
            pItems.add(itemStack);

            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "expansion_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "reconstruct_snowball");
            pItems.add(itemStack);
            itemStack = tank.getDefaultInstance();
            itemStack.getOrCreateTag().putString("Snowball", "icicle_snowball");
            pItems.add(itemStack);

            pItems.add(ItemRegister.WOOD_SNOWBALL_CLAMP.get().getDefaultInstance());
            pItems.add(ItemRegister.STONE_SNOWBALL_CLAMP.get().getDefaultInstance());
            pItems.add(ItemRegister.IRON_SNOWBALL_CLAMP.get().getDefaultInstance());
            pItems.add(ItemRegister.GOLD_SNOWBALL_CLAMP.get().getDefaultInstance());
            pItems.add(ItemRegister.DIAMOND_SNOWBALL_CLAMP.get().getDefaultInstance());
            pItems.add(ItemRegister.NETHERITE_SNOWBALL_CLAMP.get().getDefaultInstance());
            pItems.add(ItemRegister.EMERALD_SNOWBALL_CLAMP.get().getDefaultInstance());

            pItems.add(ItemRegister.BASIN.get().getDefaultInstance());
            itemStack = ItemRegister.BASIN.get().getDefaultInstance();
            itemStack.getOrCreateTag().putByte("SnowType", (byte) 1);
            pItems.add(itemStack);
            itemStack = ItemRegister.BASIN.get().getDefaultInstance();
            itemStack.getOrCreateTag().putByte("SnowType", (byte) 2);
            pItems.add(itemStack);

            pItems.add(ItemRegister.SNOWBALL_CANNON.get().getDefaultInstance());
            pItems.add(ItemRegister.POWERFUL_SNOWBALL_CANNON.get().getDefaultInstance());
            pItems.add(ItemRegister.FREEZING_SNOWBALL_CANNON.get().getDefaultInstance());
            pItems.add(ItemRegister.IMPLOSION_SNOWBALL_CANNON.get().getDefaultInstance());
            pItems.add(ItemRegister.SNOWBALL_MACHINE_GUN.get().getDefaultInstance());
            pItems.add(ItemRegister.SNOWBALL_SHOTGUN.get().getDefaultInstance());
            pItems.add(ItemRegister.SNOWMAN_IN_HAND.get().getDefaultInstance());
            pItems.add(ItemRegister.TARGET_LOCATOR.get().getDefaultInstance());

            pItems.add(ItemRegister.SNOW_BLOCK_BLENDER.get().getDefaultInstance());
            pItems.add(ItemRegister.SNOW_TRAP_SETTER.get().getDefaultInstance());
            pItems.add(ItemRegister.REPULSIVE_FIELD_GENERATOR.get().getDefaultInstance());
            pItems.add(ItemRegister.GLOVE.get().getDefaultInstance());
            pItems.add(ItemRegister.JEDI_GLOVE.get().getDefaultInstance());
            pItems.add(ItemRegister.VECTOR_INVERSION_ANCHOR.get().getDefaultInstance());
            pItems.add(ItemRegister.SNOWFLAKE_ROCKET.get().getDefaultInstance());

            pItems.add(ItemRegister.ICE_SKATES_ITEM.get().getDefaultInstance());
            pItems.add(ItemRegister.SNOW_FALL_BOOTS.get().getDefaultInstance());

            pItems.add(ItemRegister.POPSICLE.get().getDefaultInstance());
            pItems.add(ItemRegister.MILK_POPSICLE.get().getDefaultInstance());
            pItems.add(ItemRegister.VODKA.get().getDefaultInstance());

            pItems.add(ItemRegister.SMART_SNOW_BLOCK.get().getDefaultInstance());
            pItems.add(ItemRegister.SNOW_GOLEM_CONTAINER.get().getDefaultInstance());
            pItems.add(ItemRegister.SNOW_GOLEM_MODE_TWEAKER.get().getDefaultInstance());
            pItems.add(ItemRegister.CREATIVE_SNOW_GOLEM_TOOL.get().getDefaultInstance());
            pItems.add(ItemRegister.SNOW_GOLEM_CORE_REMOVER.get().getDefaultInstance());
            pItems.add(ItemRegister.BLANK_GOLEM_CORE.get().getDefaultInstance());
            pItems.add(ItemRegister.THRUST_GOLEM_CORE.get().getDefaultInstance());
            pItems.add(ItemRegister.SWIFTNESS_GOLEM_CORE.get().getDefaultInstance());
            pItems.add(ItemRegister.REGENERATION_GOLEM_CORE.get().getDefaultInstance());
            pItems.add(ItemRegister.CRITICAL_SNOW_GOLEM_CORE.get().getDefaultInstance());
            pItems.add(ItemRegister.REPULSIVE_FIELD_GOLEM_CORE.get().getDefaultInstance());
            pItems.add(ItemRegister.NEAR_TELEPORTATION_GOLEM_CORE.get().getDefaultInstance());
            pItems.add(ItemRegister.ENDER_TELEPORTATION_GOLEM_CORE.get().getDefaultInstance());
            pItems.add(ItemRegister.ACTIVE_TELEPORTATION_GOLEM_CORE.get().getDefaultInstance());

            pItems.add(ItemRegister.SUPER_POWER_CORE.get().getDefaultInstance());
            pItems.add(ItemRegister.SUPER_FROZEN_CORE.get().getDefaultInstance());
            pItems.add(ItemRegister.TRACKING_CORE.get().getDefaultInstance());
            pItems.add(ItemRegister.REPULSION_CORE.get().getDefaultInstance());
            pItems.add(ItemRegister.GRAVITY_CORE.get().getDefaultInstance());
            pItems.add(ItemRegister.UNSTABLE_CORE.get().getDefaultInstance());

            pItems.add(ItemRegister.WHITE_TEAM_LINKER.get().getDefaultInstance());
            pItems.add(ItemRegister.ORANGE_TEAM_LINKER.get().getDefaultInstance());
            pItems.add(ItemRegister.MAGENTA_TEAM_LINKER.get().getDefaultInstance());
            pItems.add(ItemRegister.LIGHT_BLUE_TEAM_LINKER.get().getDefaultInstance());
            pItems.add(ItemRegister.YELLOW_TEAM_LINKER.get().getDefaultInstance());
            pItems.add(ItemRegister.LIME_TEAM_LINKER.get().getDefaultInstance());
            pItems.add(ItemRegister.PINK_TEAM_LINKER.get().getDefaultInstance());
            pItems.add(ItemRegister.GRAY_TEAM_LINKER.get().getDefaultInstance());
            pItems.add(ItemRegister.LIGHT_GRAY_TEAM_LINKER.get().getDefaultInstance());
            pItems.add(ItemRegister.CYAN_TEAM_LINKER.get().getDefaultInstance());
            pItems.add(ItemRegister.PURPLE_TEAM_LINKER.get().getDefaultInstance());
            pItems.add(ItemRegister.BLUE_TEAM_LINKER.get().getDefaultInstance());
            pItems.add(ItemRegister.BROWN_TEAM_LINKER.get().getDefaultInstance());
            pItems.add(ItemRegister.GREEN_TEAM_LINKER.get().getDefaultInstance());
            pItems.add(ItemRegister.RED_TEAM_LINKER.get().getDefaultInstance());
            pItems.add(ItemRegister.BLACK_TEAM_LINKER.get().getDefaultInstance());
        }
    };
}
